package main

import (
	"encoding/base64"
	"flag"
	"fmt"
	"io/ioutil"
	"strings"
	"text/template"

	"github.com/gogap/builder"
	"github.com/gogap/config"
	"github.com/urfave/cli"
)

const (
	flowTempl = "cGFja2FnZSBtYWluCgppbXBvcnQgKAoJImJ5dGVzIgoJImVuY29kaW5nL2Jhc2U2NCIKCSJlbmNvZGluZy9qc29uIgoJImZtdCIKCSJpby9pb3V0aWwiCgkib3MiCgkic3RyaW5ncyIKCgkiZ2l0aHViLmNvbS9nb2dhcC9jb25maWciCgkiZ2l0aHViLmNvbS9nb2dhcC9jb250ZXh0IgoJImdpdGh1Yi5jb20vZ29nYXAvZmxvdyIKCSJnaXRodWIuY29tL2dvZ2FwL2xvZ3J1c19tYXRlIgoJImdpdGh1Yi5jb20vc2lydXBzZW4vbG9ncnVzIgoJImdpdGh1Yi5jb20vdXJmYXZlL2NsaSIKKQoKdmFyICgKCWNvbmZpZ1N0ciA9IHt7LmNvbmZpZ19zdHJ9fQopCgpmdW5jIGluaXQoKSB7CglpZiBsZW4oY29uZmlnU3RyKSA+IDAgewoJCWNvbmZpZ1N0ckRhdGEsIGVyciA6PSBiYXNlNjQuU3RkRW5jb2RpbmcuRGVjb2RlU3RyaW5nKGNvbmZpZ1N0cikKCQlpZiBlcnIgIT0gbmlsIHsKCQkJZXJyID0gZm10LkVycm9yZigiZGVjb2RlIGNvbmZpZyBzdHIgZmFpbHVyZTogJXNcbiIsIGVyci5FcnJvcigpKQoJCQlwYW5pYyhlcnIpCgkJfQoJCWNvbmZpZ1N0ciA9IHN0cmluZyhjb25maWdTdHJEYXRhKQoJfQp9CgpmdW5jIG1haW4oKSB7CgoJY29uZiA6PSBjb25maWcuTmV3Q29uZmlnKAoJCWNvbmZpZy5Db25maWdTdHJpbmcoY29uZmlnU3RyKSwKCSkKCglhcHBDb25mIDo9IGNvbmYuR2V0Q29uZmlnKCJhcHAiKQoKCWFwcCA6PSBjbGkuTmV3QXBwKCkKCglhcHAuVmVyc2lvbiA9IGFwcENvbmYuR2V0U3RyaW5nKCJ2ZXJzaW9uIiwgIjAuMC4wIikKCWFwcC5BdXRob3IgPSBhcHBDb25mLkdldFN0cmluZygiYXV0aG9yIikKCWFwcC5OYW1lID0gYXBwQ29uZi5HZXRTdHJpbmcoIm5hbWUiLCAiYXBwIikKCWFwcC5Vc2FnZSA9IGFwcENvbmYuR2V0U3RyaW5nKCJ1c2FnZSIpCglhcHAuSGVscE5hbWUgPSBhcHAuTmFtZQoKCWlmIGFwcC5WZXJzaW9uID09ICIwLjAuMCIgewoJCWFwcC5IaWRlVmVyc2lvbiA9IHRydWUKCX0KCgljb21tYW5kc0NvbmYgOj0gYXBwQ29uZi5HZXRDb25maWcoImNvbW1hbmRzIikKCglmb3IgXywga2V5IDo9IHJhbmdlIGNvbW1hbmRzQ29uZi5LZXlzKCkgewoJCWdlbmVyYXRlQ29tbWFuZHMoJmFwcC5Db21tYW5kcywga2V5LCBjb21tYW5kc0NvbmYuR2V0Q29uZmlnKGtleSkpCgl9CgoJYXBwLlJ1bkFuZEV4aXRPbkVycm9yKCkKCglyZXR1cm4KfQoKZnVuYyBuZXdBY3Rpb24obmFtZSBzdHJpbmcsIGNvbmYgY29uZmlnLkNvbmZpZ3VyYXRpb24pIGNsaS5BY3Rpb25GdW5jIHsKCglyZXR1cm4gZnVuYyhjdHggKmNsaS5Db250ZXh0KSAoZXJyIGVycm9yKSB7CgoJCWVyciA9IGxvYWRFTlYoY3R4KQoKCQlpZiBlcnIgIT0gbmlsIHsKCQkJcmV0dXJuCgkJfQoKCQlkaXNhYmxlU3RlcHMgOj0gY3R4LlN0cmluZ1NsaWNlKCJkaXNhYmxlIikKCQljb25maWdGaWxlcyA6PSBjdHguU3RyaW5nU2xpY2UoImNvbmZpZyIpCgoJCWRlZmF1bHRDb25mIDo9IGNvbmYuR2V0Q29uZmlnKCJkZWZhdWx0LWNvbmZpZyIpCgoJCW1hcENvbmZpZ3MgOj0gbWFwW3N0cmluZ11jb25maWcuQ29uZmlndXJhdGlvbnsKCQkJImRlZmF1bHQtY29uZmlnIjogZGVmYXVsdENvbmYsCgkJfQoKCQlmb3IgXywgY29uZmlnQXJnIDo9IHJhbmdlIGNvbmZpZ0ZpbGVzIHsKCQkJdiA6PSBzdHJpbmdzLlNwbGl0Tihjb25maWdBcmcsICI6IiwgMikKCQkJaWYgbGVuKHYpID09IDEgewoJCQkJYXJnc0NvbmZpZyA6PSBjb25maWcuTmV3Q29uZmlnKGNvbmZpZy5Db25maWdGaWxlKHZbMF0pKQoJCQkJbWFwQ29uZmlnc1siZGVmYXVsdC1jb25maWciXSA9IGFyZ3NDb25maWcKCQkJfSBlbHNlIGlmIGxlbih2KSA9PSAyIHsKCQkJCWFyZ3NDb25maWcgOj0gY29uZmlnLk5ld0NvbmZpZyhjb25maWcuQ29uZmlnRmlsZSh2WzFdKSkKCQkJCW1hcENvbmZpZ3NbdlswXV0gPSBhcmdzQ29uZmlnCgkJCX0KCQl9CgoJCWRlZmF1bHRDb25mID0gbWFwQ29uZmlnc1siZGVmYXVsdC1jb25maWciXQoKCQlsb2dnZXJDb25mIDo9IGRlZmF1bHRDb25mLkdldENvbmZpZygibG9nZ2VyIikKCgkJbG9ncnVzX21hdGUuSGlqYWNrKAoJCQlsb2dydXMuU3RhbmRhcmRMb2dnZXIoKSwKCQkJbG9ncnVzX21hdGUuV2l0aENvbmZpZyhsb2dnZXJDb25mKSwKCQkpCgoJCWZsb3dDdHggOj0gY29udGV4dC5OZXdDb250ZXh0KCkKCgkJY3R4TGlzdCA6PSBjdHguU3RyaW5nU2xpY2UoImN0eCIpCgkJY3R4RmlsZXMgOj0gY3R4LlN0cmluZ1NsaWNlKCJjdHgtZmlsZSIpCgoJCWxvYWRDb250ZXh0KGN0eExpc3QsIGN0eEZpbGVzLCBmbG93Q3R4KQoKCQlpbnB1dEZpbGVzIDo9IGN0eC5TdHJpbmdTbGljZSgiaW5wdXQiKQoKCQlmb3IgXywgaW5wdXRGaWxlIDo9IHJhbmdlIGlucHV0RmlsZXMgewoJCQl2YXIgaW5wdXRGaWxlRGF0YSBbXWJ5dGUKCQkJaW5wdXRGaWxlRGF0YSwgZXJyID0gaW91dGlsLlJlYWRGaWxlKGlucHV0RmlsZSkKCQkJaWYgZXJyICE9IG5pbCB7CgkJCQlyZXR1cm4KCQkJfQoKCQkJdmFyIG5hbWVWYWx1ZXMgW11mbG93Lk5hbWVWYWx1ZQoJCQllcnIgPSBqc29uLlVubWFyc2hhbChpbnB1dEZpbGVEYXRhLCAmbmFtZVZhbHVlcykKCQkJaWYgZXJyICE9IG5pbCB7CgkJCQlyZXR1cm4KCQkJfQoKCQkJZmxvdy5BcHBlbmRPdXRwdXQoZmxvd0N0eCwgbmFtZVZhbHVlcy4uLikKCQl9CgoJCXRyYW5zIDo9IGZsb3cuQmVnaW4oZmxvd0N0eCwgY29uZmlnLldpdGhDb25maWcoZGVmYXVsdENvbmYpKQoKCQlmbG93TGlzdCA6PSBjb25mLkdldFN0cmluZ0xpc3QoImZsb3ciKQoKCQlmbG93SXRlbUNvbmZpZyA6PSBjb25mLkdldENvbmZpZygiY29uZmlnIikKCgkJbWFwRGlzYWJlbFN0ZXBzIDo9IG1hcFtzdHJpbmddYm9vbHt9CgoJCWZvciBfLCBzdGVwIDo9IHJhbmdlIGRpc2FibGVTdGVwcyB7CgkJCW1hcERpc2FiZWxTdGVwc1tzdGVwXSA9IHRydWUKCQl9CgoJCWZvciBfLCBpdGVtIDo9IHJhbmdlIGZsb3dMaXN0IHsKCgkJCWhhbmRsZXJBbmRDb25mIDo9IHN0cmluZ3MuU3BsaXROKGl0ZW0sICJAIiwgMikKCgkJCW5hbWUgOj0gIiIKCQkJY29uZmlnTmFtZSA6PSAiIgoKCQkJaWYgbGVuKGhhbmRsZXJBbmRDb25mKSA9PSAyIHsKCQkJCW5hbWUgPSBoYW5kbGVyQW5kQ29uZlswXQoJCQkJY29uZmlnTmFtZSA9IGhhbmRsZXJBbmRDb25mWzFdCgkJCX0gZWxzZSB7CgkJCQluYW1lID0gaGFuZGxlckFuZENvbmZbMF0KCQkJfQoKCQkJaWYgbWFwRGlzYWJlbFN0ZXBzW2l0ZW1dIHsKCQkJCWNvbnRpbnVlCgkJCX0KCgkJCWlmIGxlbihjb25maWdOYW1lKSA+IDAgewoJCQkJaGFuZGxlckNvbmYgOj0gZmxvd0l0ZW1Db25maWcuR2V0Q29uZmlnKGNvbmZpZ05hbWUpCgoJCQkJaWYgaENvbmYsIGV4aXN0IDo9IG1hcENvbmZpZ3NbY29uZmlnTmFtZV07IGV4aXN0IHsKCQkJCQloYW5kbGVyQ29uZiA9IGhDb25mCgkJCQl9CgoJCQkJdHJhbnMuVGhlbihuYW1lLCBjb25maWcuV2l0aENvbmZpZyhoYW5kbGVyQ29uZikpCgkJCX0gZWxzZSB7CgkJCQl0cmFucy5UaGVuKG5hbWUpCgkJCX0KCQl9CgoJCWVyciA9IHRyYW5zLkNvbW1pdCgpCgoJCWlmIGVyciAhPSBuaWwgewoJCQlyZXR1cm4KCQl9CgoJCXF1aWV0IDo9IGN0eC5Cb29sKCJxdWlldCIpCgkJb3V0cHV0IDo9IGN0eC5TdHJpbmcoIm91dHB1dCIpCgoJCWlmICFxdWlldCB8fCBsZW4ob3V0cHV0KSA+IDAgewoKCQkJbmFtZVZhbHVlcyA6PSB0cmFucy5PdXRwdXQoKQoKCQkJdmFyIG91dGRhdGEgW11ieXRlCgkJCW91dGRhdGEsIGVyciA9IGpzb24uTWFyc2hhbEluZGVudCgKCQkJCW5hbWVWYWx1ZXMsCgkJCQkiIiwKCQkJCSIgICAgIikKCgkJCWlmIGVyciAhPSBuaWwgewoJCQkJcmV0dXJuCgkJCX0KCgkJCWlmIGxlbihvdXRwdXQpID09IDAgewoJCQkJaWYgbGVuKG5hbWVWYWx1ZXMpID4gMCB7CgkJCQkJZm10LlByaW50bG4oc3RyaW5nKG91dGRhdGEpKQoJCQkJfQoJCQl9IGVsc2UgewoJCQkJZXJyID0gaW91dGlsLldyaXRlRmlsZShvdXRwdXQsIG91dGRhdGEsIDA2NDQpCgkJCQlpZiBlcnIgIT0gbmlsIHsKCQkJCQlyZXR1cm4KCQkJCX0KCQkJfQoJCX0KCgkJcmV0dXJuCgl9Cn0KCmZ1bmMgbG9hZEVOVihjdHggKmNsaS5Db250ZXh0KSAoZXJyIGVycm9yKSB7CgllbnZzIDo9IGN0eC5TdHJpbmdTbGljZSgiZW52IikKCWVudkZpbGVzIDo9IGN0eC5TdHJpbmdTbGljZSgiZW52LWZpbGUiKQoKCWlmIGxlbihlbnZzKSA9PSAwICYmIGxlbihlbnZGaWxlcykgPT0gMCB7CgkJcmV0dXJuCgl9CgoJbWFwRU5WIDo9IG1hcFtzdHJpbmddc3RyaW5ne30KCglmb3IgXywgZW52IDo9IHJhbmdlIGVudnMgewoJCXYgOj0gc3RyaW5ncy5TcGxpdE4oZW52LCAiOiIsIDIpCgkJaWYgbGVuKHYpICE9IDIgewoJCQllcnIgPSBmbXQuRXJyb3JmKCJlbnYgZm9ybWF0IGVycm9yOiVzIiwgZW52KQoJCQlyZXR1cm4KCQl9CgoJCW1hcEVOVlt2WzBdXSA9IHZbMV0KCX0KCglmb3IgXywgZiA6PSByYW5nZSBlbnZGaWxlcyB7CgoJCXZhciBkYXRhIFtdYnl0ZQoJCWRhdGEsIGVyciA9IGlvdXRpbC5SZWFkRmlsZShmKQoJCWlmIGVyciAhPSBuaWwgewoJCQlyZXR1cm4KCQl9CgoJCWJ1ZiA6PSBieXRlcy5OZXdCdWZmZXIoZGF0YSkKCQlkZWNvZGVyIDo9IGpzb24uTmV3RGVjb2RlcihidWYpCgkJZGVjb2Rlci5Vc2VOdW1iZXIoKQoKCQl0bXBNYXAgOj0gbWFwW3N0cmluZ11zdHJpbmd7fQoJCWVyciA9IGRlY29kZXIuRGVjb2RlKCZ0bXBNYXApCgkJaWYgZXJyICE9IG5pbCB7CgkJCXJldHVybgoJCX0KCgkJZm9yIGssIHYgOj0gcmFuZ2UgdG1wTWFwIHsKCQkJbWFwRU5WW2tdID0gdgoJCX0KCX0KCglmb3IgaywgdiA6PSByYW5nZSBtYXBFTlYgewoJCW9zLlNldGVudihrLCB2KQoJfQoKCXJldHVybgp9CgpmdW5jIGxvYWRDb250ZXh0KGN0eExpc3QgW11zdHJpbmcsIGN0eEZpbGVzIFtdc3RyaW5nLCBmbG93Q3R4IGNvbnRleHQuQ29udGV4dCkgKGVyciBlcnJvcikgewoKCWlmIGxlbihjdHhMaXN0KSA9PSAwICYmIGxlbihjdHhGaWxlcykgPT0gMCB7CgkJcmV0dXJuCgl9CgoJbWFwQ3R4IDo9IG1hcFtzdHJpbmddc3RyaW5ne30KCglmb3IgXywgYyA6PSByYW5nZSBjdHhMaXN0IHsKCQl2IDo9IHN0cmluZ3MuU3BsaXROKGMsICI6IiwgMikKCQlpZiBsZW4odikgIT0gMiB7CgkJCWVyciA9IGZtdC5FcnJvcmYoImN0eCBmb3JtYXQgZXJyb3I6JXMiLCBjKQoJCQlyZXR1cm4KCQl9CgoJCW1hcEN0eFt2WzBdXSA9IHZbMV0KCX0KCglmb3IgXywgZiA6PSByYW5nZSBjdHhGaWxlcyB7CgoJCXZhciBkYXRhIFtdYnl0ZQoJCWRhdGEsIGVyciA9IGlvdXRpbC5SZWFkRmlsZShmKQoJCWlmIGVyciAhPSBuaWwgewoJCQlyZXR1cm4KCQl9CgoJCWJ1ZiA6PSBieXRlcy5OZXdCdWZmZXIoZGF0YSkKCQlkZWNvZGVyIDo9IGpzb24uTmV3RGVjb2RlcihidWYpCgkJZGVjb2Rlci5Vc2VOdW1iZXIoKQoKCQl0bXBNYXAgOj0gbWFwW3N0cmluZ11zdHJpbmd7fQoJCWVyciA9IGRlY29kZXIuRGVjb2RlKCZ0bXBNYXApCgkJaWYgZXJyICE9IG5pbCB7CgkJCXJldHVybgoJCX0KCgkJZm9yIGssIHYgOj0gcmFuZ2UgdG1wTWFwIHsKCQkJbWFwQ3R4W2tdID0gdgoJCX0KCX0KCglmb3IgaywgdiA6PSByYW5nZSBtYXBDdHggewoJCWZsb3dDdHguV2l0aFZhbHVlKGssIHYpCgl9CgoJcmV0dXJuCn0KCmZ1bmMgZ2VuZXJhdGVDb21tYW5kcyhjbWRzICpbXWNsaS5Db21tYW5kLCBuYW1lIHN0cmluZywgY29uZiBjb25maWcuQ29uZmlndXJhdGlvbikgewoKCWtleXMgOj0gY29uZi5LZXlzKCkKCglpZiBsZW4oa2V5cykgPT0gMCB7CgkJcmV0dXJuCgl9CgoJb2JqQ291bnQgOj0gMAoJZm9yIF8sIGtleSA6PSByYW5nZSBrZXlzIHsKCQlpZiBjb25mLklzT2JqZWN0KGtleSkgfHwga2V5ID09ICJ1c2FnZSIgewoJCQlvYmpDb3VudCsrCgkJfQoJfQoKCS8vIENvbW1hbmQKCWlmIG9iakNvdW50ICE9IGxlbihrZXlzKSB7CgkJKmNtZHMgPSBhcHBlbmQoKmNtZHMsCgkJCWNsaS5Db21tYW5kewoJCQkJTmFtZTogIG5hbWUsCgkJCQlVc2FnZTogY29uZi5HZXRTdHJpbmcoInVzYWdlIiksCgkJCQlGbGFnczogW11jbGkuRmxhZ3sKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImRpc2FibGUsIGQiLAoJCQkJCQlVc2FnZTogImRpc2FibGUgc3RlcHMsIGUuZy46IC1kIGRldm9wcy5hbGl5dW4uY3MuY2x1c3Rlci5kZWxldGVkLndhaXQgLWQgZGV2b3BzLmFsaXl1bi5jcy5jbHVzdGVyLnJ1bm5pbmcud2FpdCIsCgkJCQkJfSwKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImNvbmZpZywgYyIsCgkJCQkJCVVzYWdlOiAidXNlIHNwZWNpZmllZCBjb25maWcgdG8gZGVmYXVsdCBjb25maWciLAoJCQkJCX0sCgkJCQkJY2xpLlN0cmluZ1NsaWNlRmxhZ3sKCQkJCQkJTmFtZTogICJlbnYiLAoJCQkJCQlVc2FnZTogImUuZy46IC0tZW52IFVTRVI6dGVzdCAtLWVudiBQV0Q6YXNkZiIsCgkJCQkJfSwKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImN0eCIsCgkJCQkJCVVzYWdlOiAiZS5nLjogLS1jdHggY29kZTpnb2dhcCAtLWVudiBoZWxsbzp3b3JsZCIsCgkJCQkJfSwKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImVudi1maWxlIiwKCQkJCQkJVXNhZ2U6ICJlLmcuOiAtLWVudi1maWxlIGEuanNvbiAtLWVudi1maWxlIGIuanNvbiIsCgkJCQkJfSwKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImlucHV0LCBpIiwKCQkJCQkJVXNhZ2U6ICJpbnB1dCBmaWxlIGZyb20gb3RoZXIncyBvdXRwdXQgZm9yIGluaXQgdGhpcyBmbG93LCBlLmcuOiAtaSBvdXRwdXQxLmpzb24gLWkgb3V0cHV0Mi5qc29uIiwKCQkJCQl9LAoJCQkJCWNsaS5TdHJpbmdGbGFnewoJCQkJCQlOYW1lOiAgIm91dHB1dCwgbyIsCgkJCQkJCVVzYWdlOiAiZmlsZW5hbWUgb2Ygb3V0cHV0IiwKCQkJCQl9LAoJCQkJCWNsaS5Cb29sRmxhZ3sKCQkJCQkJTmFtZTogICJxdWlldCwgcSIsCgkJCQkJCVVzYWdlOiAiYmUgcXVpZXQsIG5vIG91dHB1dCBkYXRhIHByaW50IiwKCQkJCQl9LAoJCQkJfSwKCQkJCUFjdGlvbjogbmV3QWN0aW9uKG5hbWUsIGNvbmYpLAoJCQl9LAoJCSkKCgkJcmV0dXJuCgl9CgoJdmFyIHN1YkNvbW1hbmRzIFtdY2xpLkNvbW1hbmQKCglmb3IgXywga2V5IDo9IHJhbmdlIGNvbmYuS2V5cygpIHsKCgkJaWYga2V5ID09ICJ1c2FnZSIgewoJCQljb250aW51ZQoJCX0KCgkJZ2VuZXJhdGVDb21tYW5kcygmc3ViQ29tbWFuZHMsIGtleSwgY29uZi5HZXRDb25maWcoa2V5KSkKCgl9CgoJY3VycmVudENvbW1hbmQgOj0gY2xpLkNvbW1hbmR7CgkJTmFtZTogICAgICAgIG5hbWUsCgkJVXNhZ2U6ICAgICAgIGNvbmYuR2V0U3RyaW5nKCJ1c2FnZSIpLAoJCVN1YmNvbW1hbmRzOiBzdWJDb21tYW5kcywKCX0KCgkqY21kcyA9IGFwcGVuZCgqY21kcywgY3VycmVudENvbW1hbmQpCn0K"
)

func main() {
	app := cli.NewApp()

	app.Name = "go-flow"
	app.HelpName = "go-flow"
	app.HideVersion = true

	app.Commands = cli.Commands{
		cli.Command{
			Name:  "build",
			Usage: "build your own flow into binary",
			Flags: []cli.Flag{
				cli.StringFlag{
					Name:  "config",
					Usage: "flow config file",
				},
			},
			Action: build,
		},

		cli.Command{
			Name:  "run",
			Usage: "run flow",
			Flags: []cli.Flag{
				cli.StringFlag{
					Name:  "config",
					Usage: "flow config file",
				},
			},
			Action:          run,
			SkipFlagParsing: true,
			SkipArgReorder:  true,
		},
	}

	app.Flags = []cli.Flag{
		cli.BoolFlag{
			Name:  "verbose, v",
			Usage: "be verbose",
		},
	}

	app.RunAndExitOnError()
}

func createBuilder(appName string, verboseOfGoBuild, verboseOfGoGet bool, conf config.Configuration) (bu *builder.Builder, err error) {

	argsConf := ""

	if verboseOfGoGet {
		argsConf += "go-get = [\"-v\"]\n"
	}

	if verboseOfGoBuild {
		argsConf += "go-build = [\"-v\"]\n"
	}

	buildConfStr := fmt.Sprintf(`%s {
packages = %s
build.args {
    %s
  }
}`, appName,
		toPkgList(conf.GetStringList("packages")),
		argsConf,
	)

	goTmpl, err := base64.StdEncoding.DecodeString(flowTempl)
	if err != nil {
		return
	}

	tmpl, err := template.New(appName).Parse(string(goTmpl))
	if err != nil {
		return
	}

	b, err := builder.NewBuilder(
		builder.ConfigString(buildConfStr),
		builder.Template(tmpl),
	)

	if err != nil {
		return
	}

	bu = b
	return
}

func toPkgList(list []string) string {

	var values []string

	for _, item := range list {
		values = append(values, fmt.Sprintf("\"%s\"", item))
	}

	return "[" + strings.Join(values, ",") + "]"
}

func build(ctx *cli.Context) (err error) {

	configFile := ctx.String("config")

	if len(configFile) == 0 {
		err = fmt.Errorf("please input config file")
		return
	}

	conf := config.NewConfig(config.ConfigFile(configFile))

	appName := conf.GetString("app.name", "app")

	verbose := ctx.Parent().Bool("verbose")

	b, err := createBuilder(appName, verbose, verbose, conf)
	if err != nil {
		return
	}

	configData, err := ioutil.ReadFile(configFile)
	if err != nil {
		return
	}

	err = b.Build(map[string]interface{}{"config_str": fmt.Sprintf("`%s`", string(configData))}, appName)

	return
}

func run(ctx *cli.Context) (err error) {

	set := flag.NewFlagSet("run", 0)

	confArg := set.String("config", "", "flow config file")

	err = set.Parse(ctx.Args()[0:2])
	if err != nil {
		return
	}

	configFile := *confArg

	if len(configFile) == 0 {
		err = fmt.Errorf("please input config file")
		return
	}

	conf := config.NewConfig(config.ConfigFile(configFile))

	appName := conf.GetString("app.name", "app")

	verbose := ctx.Parent().Bool("verbose")

	b, err := createBuilder(appName, false, verbose, conf)
	if err != nil {
		return
	}

	configData, err := ioutil.ReadFile(configFile)
	if err != nil {
		return
	}

	base64ConfStr := base64.StdEncoding.EncodeToString(configData)

	err = b.Run(map[string]interface{}{"config_str": fmt.Sprintf("`%s`", base64ConfStr)}, appName, ctx.Args()[2:])

	return
}
