package main

import (
	"encoding/base64"
	"flag"
	"fmt"
	"io/ioutil"
	"text/template"

	"github.com/gogap/builder"
	"github.com/gogap/config"
	"github.com/urfave/cli"
)

const (
	flowTempl = "cGFja2FnZSBtYWluCgppbXBvcnQgKAoJImJ5dGVzIgoJImVuY29kaW5nL2pzb24iCgkiZm10IgoJImlvL2lvdXRpbCIKCSJvcyIKCSJzdHJpbmdzIgoKCSJnaXRodWIuY29tL2dvZ2FwL2NvbmZpZyIKCSJnaXRodWIuY29tL2dvZ2FwL2NvbnRleHQiCgkiZ2l0aHViLmNvbS9nb2dhcC9mbG93IgoJImdpdGh1Yi5jb20vZ29nYXAvbG9ncnVzX21hdGUiCgkiZ2l0aHViLmNvbS9zaXJ1cHNlbi9sb2dydXMiCgkiZ2l0aHViLmNvbS91cmZhdmUvY2xpIgopCgp2YXIgKAoJY29uZmlnU3RyID0ge3suY29uZmlnX3N0cn19CikKCmZ1bmMgbWFpbigpIHsKCgljb25mIDo9IGNvbmZpZy5OZXdDb25maWcoCgkJY29uZmlnLkNvbmZpZ1N0cmluZyhjb25maWdTdHIpLAoJKQoKCWFwcENvbmYgOj0gY29uZi5HZXRDb25maWcoImFwcCIpCgoJYXBwIDo9IGNsaS5OZXdBcHAoKQoKCWFwcC5WZXJzaW9uID0gYXBwQ29uZi5HZXRTdHJpbmcoInZlcnNpb24iLCAiMC4wLjAiKQoJYXBwLkF1dGhvciA9IGFwcENvbmYuR2V0U3RyaW5nKCJhdXRob3IiKQoJYXBwLk5hbWUgPSBhcHBDb25mLkdldFN0cmluZygibmFtZSIsICJhcHAiKQoJYXBwLlVzYWdlID0gYXBwQ29uZi5HZXRTdHJpbmcoInVzYWdlIikKCWFwcC5IZWxwTmFtZSA9IGFwcC5OYW1lCgoJaWYgYXBwLlZlcnNpb24gPT0gIjAuMC4wIiB7CgkJYXBwLkhpZGVWZXJzaW9uID0gdHJ1ZQoJfQoKCWNvbW1hbmRzQ29uZiA6PSBhcHBDb25mLkdldENvbmZpZygiY29tbWFuZHMiKQoKCWZvciBfLCBrZXkgOj0gcmFuZ2UgY29tbWFuZHNDb25mLktleXMoKSB7CgkJZ2VuZXJhdGVDb21tYW5kcygmYXBwLkNvbW1hbmRzLCBrZXksIGNvbW1hbmRzQ29uZi5HZXRDb25maWcoa2V5KSkKCX0KCglhcHAuUnVuQW5kRXhpdE9uRXJyb3IoKQoKCXJldHVybgp9CgpmdW5jIG5ld0FjdGlvbihuYW1lIHN0cmluZywgY29uZiBjb25maWcuQ29uZmlndXJhdGlvbikgY2xpLkFjdGlvbkZ1bmMgewoKCXJldHVybiBmdW5jKGN0eCAqY2xpLkNvbnRleHQpIChlcnIgZXJyb3IpIHsKCgkJZXJyID0gbG9hZEVOVihjdHgpCgoJCWlmIGVyciAhPSBuaWwgewoJCQlyZXR1cm4KCQl9CgoJCWRpc2FibGVTdGVwcyA6PSBjdHguU3RyaW5nU2xpY2UoImRpc2FibGUiKQoJCWNvbmZpZ0ZpbGVzIDo9IGN0eC5TdHJpbmdTbGljZSgiY29uZmlnIikKCgkJZGVmYXVsdENvbmYgOj0gY29uZi5HZXRDb25maWcoImRlZmF1bHQtY29uZmlnIikKCgkJbWFwQ29uZmlncyA6PSBtYXBbc3RyaW5nXWNvbmZpZy5Db25maWd1cmF0aW9uewoJCQkiZGVmYXVsdC1jb25maWciOiBkZWZhdWx0Q29uZiwKCQl9CgoJCWZvciBfLCBjb25maWdBcmcgOj0gcmFuZ2UgY29uZmlnRmlsZXMgewoJCQl2IDo9IHN0cmluZ3MuU3BsaXROKGNvbmZpZ0FyZywgIjoiLCAyKQoJCQlpZiBsZW4odikgPT0gMSB7CgkJCQlhcmdzQ29uZmlnIDo9IGNvbmZpZy5OZXdDb25maWcoY29uZmlnLkNvbmZpZ0ZpbGUodlswXSkpCgkJCQltYXBDb25maWdzWyJkZWZhdWx0LWNvbmZpZyJdID0gYXJnc0NvbmZpZwoJCQl9IGVsc2UgaWYgbGVuKHYpID09IDIgewoJCQkJYXJnc0NvbmZpZyA6PSBjb25maWcuTmV3Q29uZmlnKGNvbmZpZy5Db25maWdGaWxlKHZbMV0pKQoJCQkJbWFwQ29uZmlnc1t2WzBdXSA9IGFyZ3NDb25maWcKCQkJfQoJCX0KCgkJZGVmYXVsdENvbmYgPSBtYXBDb25maWdzWyJkZWZhdWx0LWNvbmZpZyJdCgoJCWxvZ2dlckNvbmYgOj0gZGVmYXVsdENvbmYuR2V0Q29uZmlnKCJsb2dnZXIiKQoKCQlsb2dydXNfbWF0ZS5IaWphY2soCgkJCWxvZ3J1cy5TdGFuZGFyZExvZ2dlcigpLAoJCQlsb2dydXNfbWF0ZS5XaXRoQ29uZmlnKGxvZ2dlckNvbmYpLAoJCSkKCgkJZmxvd0N0eCA6PSBjb250ZXh0Lk5ld0NvbnRleHQoKQoKCQljdHhMaXN0IDo9IGN0eC5TdHJpbmdTbGljZSgiY3R4IikKCQljdHhGaWxlcyA6PSBjdHguU3RyaW5nU2xpY2UoImN0eC1maWxlIikKCgkJbG9hZENvbnRleHQoY3R4TGlzdCwgY3R4RmlsZXMsIGZsb3dDdHgpCgoJCXRyYW5zIDo9IGZsb3cuQmVnaW4oZmxvd0N0eCwgY29uZmlnLldpdGhDb25maWcoZGVmYXVsdENvbmYpKQoKCQlmbG93TGlzdCA6PSBjb25mLkdldFN0cmluZ0xpc3QoImZsb3ciKQoKCQlmbG93SXRlbUNvbmZpZyA6PSBjb25mLkdldENvbmZpZygiY29uZmlnIikKCgkJbWFwRGlzYWJlbFN0ZXBzIDo9IG1hcFtzdHJpbmddYm9vbHt9CgoJCWZvciBfLCBzdGVwIDo9IHJhbmdlIGRpc2FibGVTdGVwcyB7CgkJCW1hcERpc2FiZWxTdGVwc1tzdGVwXSA9IHRydWUKCQl9CgoJCWZvciBfLCBpdGVtIDo9IHJhbmdlIGZsb3dMaXN0IHsKCgkJCWhhbmRsZXJBbmRDb25mIDo9IHN0cmluZ3MuU3BsaXROKGl0ZW0sICJAIiwgMikKCgkJCW5hbWUgOj0gIiIKCQkJY29uZmlnTmFtZSA6PSAiIgoKCQkJaWYgbGVuKGhhbmRsZXJBbmRDb25mKSA9PSAyIHsKCQkJCW5hbWUgPSBoYW5kbGVyQW5kQ29uZlswXQoJCQkJY29uZmlnTmFtZSA9IGhhbmRsZXJBbmRDb25mWzFdCgkJCX0gZWxzZSB7CgkJCQluYW1lID0gaGFuZGxlckFuZENvbmZbMF0KCQkJfQoKCQkJaWYgbWFwRGlzYWJlbFN0ZXBzW2l0ZW1dIHsKCQkJCWNvbnRpbnVlCgkJCX0KCgkJCWlmIGxlbihjb25maWdOYW1lKSA+IDAgewoJCQkJaGFuZGxlckNvbmYgOj0gZmxvd0l0ZW1Db25maWcuR2V0Q29uZmlnKGNvbmZpZ05hbWUpCgoJCQkJaWYgaENvbmYsIGV4aXN0IDo9IG1hcENvbmZpZ3NbY29uZmlnTmFtZV07IGV4aXN0IHsKCQkJCQloYW5kbGVyQ29uZiA9IGhDb25mCgkJCQl9CgoJCQkJdHJhbnMuVGhlbihuYW1lLCBjb25maWcuV2l0aENvbmZpZyhoYW5kbGVyQ29uZikpCgkJCX0gZWxzZSB7CgkJCQl0cmFucy5UaGVuKG5hbWUpCgkJCX0KCQl9CgoJCWVyciA9IHRyYW5zLkNvbW1pdCgpCgoJCWlmIGVyciAhPSBuaWwgewoJCQlyZXR1cm4KCQl9CgoJCXF1aWV0IDo9IGN0eC5Cb29sKCJxdWlldCIpCgkJb3V0cHV0IDo9IGN0eC5TdHJpbmcoIm91dHB1dCIpCgoJCWlmICFxdWlldCB8fCBsZW4ob3V0cHV0KSA+IDAgewoKCQkJbmFtZVZhbHVlcyA6PSB0cmFucy5PdXRwdXQoKQoKCQkJdmFyIG91dGRhdGEgW11ieXRlCgkJCW91dGRhdGEsIGVyciA9IGpzb24uTWFyc2hhbEluZGVudCgKCQkJCW5hbWVWYWx1ZXMsCgkJCQkiIiwKCQkJCSIgICAgIikKCgkJCWlmIGVyciAhPSBuaWwgewoJCQkJcmV0dXJuCgkJCX0KCgkJCWlmIGxlbihvdXRwdXQpID09IDAgewoJCQkJaWYgbGVuKG5hbWVWYWx1ZXMpID4gMCB7CgkJCQkJZm10LlByaW50bG4oc3RyaW5nKG91dGRhdGEpKQoJCQkJfQoJCQl9IGVsc2UgewoJCQkJZXJyID0gaW91dGlsLldyaXRlRmlsZShvdXRwdXQsIG91dGRhdGEsIDA2NDQpCgkJCQlpZiBlcnIgIT0gbmlsIHsKCQkJCQlyZXR1cm4KCQkJCX0KCQkJfQoJCX0KCgkJcmV0dXJuCgl9Cn0KCmZ1bmMgbG9hZEVOVihjdHggKmNsaS5Db250ZXh0KSAoZXJyIGVycm9yKSB7CgllbnZzIDo9IGN0eC5TdHJpbmdTbGljZSgiZW52IikKCWVudkZpbGVzIDo9IGN0eC5TdHJpbmdTbGljZSgiZW52LWZpbGUiKQoKCWlmIGxlbihlbnZzKSA9PSAwICYmIGxlbihlbnZGaWxlcykgPT0gMCB7CgkJcmV0dXJuCgl9CgoJbWFwRU5WIDo9IG1hcFtzdHJpbmddc3RyaW5ne30KCglmb3IgXywgZW52IDo9IHJhbmdlIGVudnMgewoJCXYgOj0gc3RyaW5ncy5TcGxpdE4oZW52LCAiOiIsIDIpCgkJaWYgbGVuKHYpICE9IDIgewoJCQllcnIgPSBmbXQuRXJyb3JmKCJlbnYgZm9ybWF0IGVycm9yOiVzIiwgZW52KQoJCQlyZXR1cm4KCQl9CgoJCW1hcEVOVlt2WzBdXSA9IHZbMV0KCX0KCglmb3IgXywgZiA6PSByYW5nZSBlbnZGaWxlcyB7CgoJCXZhciBkYXRhIFtdYnl0ZQoJCWRhdGEsIGVyciA9IGlvdXRpbC5SZWFkRmlsZShmKQoJCWlmIGVyciAhPSBuaWwgewoJCQlyZXR1cm4KCQl9CgoJCWJ1ZiA6PSBieXRlcy5OZXdCdWZmZXIoZGF0YSkKCQlkZWNvZGVyIDo9IGpzb24uTmV3RGVjb2RlcihidWYpCgkJZGVjb2Rlci5Vc2VOdW1iZXIoKQoKCQl0bXBNYXAgOj0gbWFwW3N0cmluZ11zdHJpbmd7fQoJCWVyciA9IGRlY29kZXIuRGVjb2RlKCZ0bXBNYXApCgkJaWYgZXJyICE9IG5pbCB7CgkJCXJldHVybgoJCX0KCgkJZm9yIGssIHYgOj0gcmFuZ2UgdG1wTWFwIHsKCQkJbWFwRU5WW2tdID0gdgoJCX0KCX0KCglmb3IgaywgdiA6PSByYW5nZSBtYXBFTlYgewoJCW9zLlNldGVudihrLCB2KQoJfQoKCXJldHVybgp9CgpmdW5jIGxvYWRDb250ZXh0KGN0eExpc3QgW11zdHJpbmcsIGN0eEZpbGVzIFtdc3RyaW5nLCBmbG93Q3R4IGNvbnRleHQuQ29udGV4dCkgKGVyciBlcnJvcikgewoKCWlmIGxlbihjdHhMaXN0KSA9PSAwICYmIGxlbihjdHhGaWxlcykgPT0gMCB7CgkJcmV0dXJuCgl9CgoJbWFwQ3R4IDo9IG1hcFtzdHJpbmddc3RyaW5ne30KCglmb3IgXywgYyA6PSByYW5nZSBjdHhMaXN0IHsKCQl2IDo9IHN0cmluZ3MuU3BsaXROKGMsICI6IiwgMikKCQlpZiBsZW4odikgIT0gMiB7CgkJCWVyciA9IGZtdC5FcnJvcmYoImN0eCBmb3JtYXQgZXJyb3I6JXMiLCBjKQoJCQlyZXR1cm4KCQl9CgoJCW1hcEN0eFt2WzBdXSA9IHZbMV0KCX0KCglmb3IgXywgZiA6PSByYW5nZSBjdHhGaWxlcyB7CgoJCXZhciBkYXRhIFtdYnl0ZQoJCWRhdGEsIGVyciA9IGlvdXRpbC5SZWFkRmlsZShmKQoJCWlmIGVyciAhPSBuaWwgewoJCQlyZXR1cm4KCQl9CgoJCWJ1ZiA6PSBieXRlcy5OZXdCdWZmZXIoZGF0YSkKCQlkZWNvZGVyIDo9IGpzb24uTmV3RGVjb2RlcihidWYpCgkJZGVjb2Rlci5Vc2VOdW1iZXIoKQoKCQl0bXBNYXAgOj0gbWFwW3N0cmluZ11zdHJpbmd7fQoJCWVyciA9IGRlY29kZXIuRGVjb2RlKCZ0bXBNYXApCgkJaWYgZXJyICE9IG5pbCB7CgkJCXJldHVybgoJCX0KCgkJZm9yIGssIHYgOj0gcmFuZ2UgdG1wTWFwIHsKCQkJbWFwQ3R4W2tdID0gdgoJCX0KCX0KCglmb3IgaywgdiA6PSByYW5nZSBtYXBDdHggewoJCWZsb3dDdHguV2l0aFZhbHVlKGssIHYpCgl9CgoJcmV0dXJuCn0KCmZ1bmMgZ2VuZXJhdGVDb21tYW5kcyhjbWRzICpbXWNsaS5Db21tYW5kLCBuYW1lIHN0cmluZywgY29uZiBjb25maWcuQ29uZmlndXJhdGlvbikgewoKCWtleXMgOj0gY29uZi5LZXlzKCkKCglpZiBsZW4oa2V5cykgPT0gMCB7CgkJcmV0dXJuCgl9CgoJb2JqQ291bnQgOj0gMAoJZm9yIF8sIGtleSA6PSByYW5nZSBrZXlzIHsKCQlpZiBjb25mLklzT2JqZWN0KGtleSkgfHwga2V5ID09ICJ1c2FnZSIgewoJCQlvYmpDb3VudCsrCgkJfQoJfQoKCS8vIENvbW1hbmQKCWlmIG9iakNvdW50ICE9IGxlbihrZXlzKSB7CgkJKmNtZHMgPSBhcHBlbmQoKmNtZHMsCgkJCWNsaS5Db21tYW5kewoJCQkJTmFtZTogIG5hbWUsCgkJCQlVc2FnZTogY29uZi5HZXRTdHJpbmcoInVzYWdlIiksCgkJCQlGbGFnczogW11jbGkuRmxhZ3sKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImRpc2FibGUsIGQiLAoJCQkJCQlVc2FnZTogImRpc2FibGUgc3RlcHMsIGUuZy46IC1kIGRldm9wcy5hbGl5dW4uY3MuY2x1c3Rlci5kZWxldGVkLndhaXQgLWQgZGV2b3BzLmFsaXl1bi5jcy5jbHVzdGVyLnJ1bm5pbmcud2FpdCIsCgkJCQkJfSwKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImNvbmZpZywgYyIsCgkJCQkJCVVzYWdlOiAidXNlIHNwZWNpZmllZCBjb25maWcgdG8gZGVmYXVsdCBjb25maWciLAoJCQkJCX0sCgkJCQkJY2xpLlN0cmluZ1NsaWNlRmxhZ3sKCQkJCQkJTmFtZTogICJlbnYiLAoJCQkJCQlVc2FnZTogImUuZy46IC0tZW52IFVTRVI6dGVzdCAtLWVudiBQV0Q6YXNkZiIsCgkJCQkJfSwKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImN0eCIsCgkJCQkJCVVzYWdlOiAiZS5nLjogLS1jdHggY29kZTpnb2dhcCAtLWVudiBoZWxsbzp3b3JsZCIsCgkJCQkJfSwKCQkJCQljbGkuU3RyaW5nU2xpY2VGbGFnewoJCQkJCQlOYW1lOiAgImVudi1maWxlIiwKCQkJCQkJVXNhZ2U6ICJlLmcuOiAtLWVudi1maWxlIGEuanNvbiAtLWVudi1maWxlIGIuanNvbiIsCgkJCQkJfSwKCQkJCQljbGkuQm9vbEZsYWd7CgkJCQkJCU5hbWU6ICAicXVpZXQsIHEiLAoJCQkJCQlVc2FnZTogImJlIHF1aWV0LCBubyBvdXRwdXQgZGF0YSBwcmludCIsCgkJCQkJfSwKCQkJCQljbGkuU3RyaW5nRmxhZ3sKCQkJCQkJTmFtZTogICJvdXRwdXQsIG8iLAoJCQkJCQlVc2FnZTogImZpbGVuYW1lIG91dCBvdXRwdXQiLAoJCQkJCX0sCgkJCQl9LAoJCQkJQWN0aW9uOiBuZXdBY3Rpb24obmFtZSwgY29uZiksCgkJCX0sCgkJKQoKCQlyZXR1cm4KCX0KCgl2YXIgc3ViQ29tbWFuZHMgW11jbGkuQ29tbWFuZAoKCWZvciBfLCBrZXkgOj0gcmFuZ2UgY29uZi5LZXlzKCkgewoKCQlpZiBrZXkgPT0gInVzYWdlIiB7CgkJCWNvbnRpbnVlCgkJfQoKCQlnZW5lcmF0ZUNvbW1hbmRzKCZzdWJDb21tYW5kcywga2V5LCBjb25mLkdldENvbmZpZyhrZXkpKQoKCX0KCgljdXJyZW50Q29tbWFuZCA6PSBjbGkuQ29tbWFuZHsKCQlOYW1lOiAgICAgICAgbmFtZSwKCQlVc2FnZTogICAgICAgY29uZi5HZXRTdHJpbmcoInVzYWdlIiksCgkJU3ViY29tbWFuZHM6IHN1YkNvbW1hbmRzLAoJfQoKCSpjbWRzID0gYXBwZW5kKCpjbWRzLCBjdXJyZW50Q29tbWFuZCkKfQ=="
)

func main() {
	app := cli.NewApp()

	app.Name = "go-flow"
	app.HelpName = "go-flow"
	app.HideVersion = true

	app.Commands = cli.Commands{
		cli.Command{
			Name:  "build",
			Usage: "build your own flow into binary",
			Flags: []cli.Flag{
				cli.StringFlag{
					Name:  "config",
					Usage: "flow config file",
				},
			},
			Action: build,
		},

		cli.Command{
			Name:  "run",
			Usage: "run flow",
			Flags: []cli.Flag{
				cli.StringFlag{
					Name:  "config",
					Usage: "flow config file",
				},
			},
			Action:          run,
			SkipFlagParsing: true,
			SkipArgReorder:  true,
		},
	}

	app.Flags = []cli.Flag{
		cli.BoolFlag{
			Name:  "verbose, v",
			Usage: "be verbose",
		},
	}

	app.RunAndExitOnError()
}

func createBuilder(appName string, verboseOfGoBuild, verboseOfGoGet bool, conf config.Configuration) (bu *builder.Builder, err error) {

	argsConf := ""

	if verboseOfGoGet {
		argsConf += "go-get = [\"-v\"]\n"
	}

	if verboseOfGoBuild {
		argsConf += "go-build = [\"-v\"]\n"
	}

	buildConfStr := fmt.Sprintf(`%s {
packages = %s
build.args {
    %s
  }
}`, appName, conf.GetStringList("packages"), argsConf)

	goTmpl, err := base64.StdEncoding.DecodeString(flowTempl)
	if err != nil {
		return
	}

	tmpl, err := template.New(appName).Parse(string(goTmpl))
	if err != nil {
		return
	}

	b, err := builder.NewBuilder(
		builder.ConfigString(buildConfStr),
		builder.Template(tmpl),
	)

	if err != nil {
		return
	}

	bu = b
	return
}

func build(ctx *cli.Context) (err error) {

	configFile := ctx.String("config")

	if len(configFile) == 0 {
		err = fmt.Errorf("please input config file")
		return
	}

	conf := config.NewConfig(config.ConfigFile(configFile))

	appName := conf.GetString("app.name", "app")

	verbose := ctx.Parent().Bool("verbose")

	b, err := createBuilder(appName, verbose, verbose, conf)
	if err != nil {
		return
	}

	configData, err := ioutil.ReadFile(configFile)
	if err != nil {
		return
	}

	err = b.Build(map[string]interface{}{"config_str": fmt.Sprintf("`%s`", string(configData))}, appName)

	return
}

func run(ctx *cli.Context) (err error) {

	set := flag.NewFlagSet("run", 0)

	confArg := set.String("config", "", "flow config file")

	err = set.Parse(ctx.Args()[0:2])
	if err != nil {
		return
	}

	configFile := *confArg

	if len(configFile) == 0 {
		err = fmt.Errorf("please input config file")
		return
	}

	conf := config.NewConfig(config.ConfigFile(configFile))

	appName := conf.GetString("app.name", "app")

	verbose := ctx.Parent().Bool("verbose")

	b, err := createBuilder(appName, false, verbose, conf)
	if err != nil {
		return
	}

	configData, err := ioutil.ReadFile(configFile)
	if err != nil {
		return
	}

	err = b.Run(map[string]interface{}{"config_str": fmt.Sprintf("`%s`", string(configData))}, appName, ctx.Args()[2:])

	return
}
